### ISSUE TITLE
[feature] parse all JSON credential content into plain secret

### ISSUE THREAD

**Issue by cdlliuy** [IBM/cloud-operators#123]
When playing with Cloud object storage service,   its credential looks like:
```
{
  "apikey": "xxxxx",
  "cos_hmac_keys": {
    "access_key_id": "xxxx",
    "secret_access_key": "xxxx"
  },
  "endpoints": "https://control.cloud-object-storage.cloud.ibm.com/v2/endpoints",
  "iam_apikey_description": "xxxx",
  "iam_apikey_name": "test-cos-crendentail",
  "iam_role_crn": "xxxx",
  "iam_serviceid_crn": "xxxx",
  "resource_instance_id": "xxxx"
}
```
In current implementation,  the `cos_hmac_keys` are saved as the JSON format in kube secret. 
```
apiVersion: v1
data:
  apikey: xxx
  cos_hmac_keys: xxx
  ....
kind: Secret
```

Is that possible to parse the inner JSON as well  to create secret as below format ?
```
apiVersion: v1
data:
  apikey: xxx
  cos_hmac_keys.access_key_id: xxx
 cos_hmac_keys.secret_access_key: xxx
  ....
kind: Secret
```

**Comment by ZhuangYuZY** [comment]
Discussion in https://ibm-cloudplatform.slack.com/archives/CU3795MNE/p1587454501008000

**Comment by ZhuangYuZY** [comment]
From Mandana Vaziri  and @pdettori 

The user will be able to specify what they want in the secret explicitly (optionally) by having the following in the spec of the binding resource:
```
secret-content:
- name: cos-hmac-keys-access-key-id
  value: <path-to-value-in-credentials>
- name: cos-hmac-keys-secret-access-key
  value: <path-to-value-in-credentials>
```
where the paths will be given using go templates.
This would be accomodate other use cases we’ve seen where the credentials are very complicated and that also need some data transformation.
Our Binding controller will take this spec and produce the correct data in the secret
