### ISSUE TITLE
secretName in Binding spec was not used for secret name

### ISSUE THREAD

**Issue by lluan444** [IBM/cloud-operators#16]
Tried the binding operator with the following yaml. It appears that the operator did not name the secret with `secretName` as specified in yaml. The secret was named `binding-messagehub` instead of  `laura-messagehub-secret`.
```
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: binding-messagehub
spec:
  serviceName: mymessagehub
  secretName: laura-messagehub-secret
```
