### ISSUE TITLE
Unable to provision compose-for-mysql

### ISSUE THREAD

**Issue by chkhd** [IBM/cloud-operators#161]
I am trying to provision MySQL database in Compose. I have an Org/Space in appropriate region.

```yaml
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: mysql-test
spec:
  plan: standard
  serviceClass: compose-for-mysql
```

However I get an error message:

```
Message:  Failed: No deployment found for service plan standard at location eu-de. Valid location(s) are: [].
Use service instance example if the service is a Cloud Foundry service
```

I already run two databases in that region, created from web-console. Besides, there are deployments clearly listed for that plan in eu-de:

```
ibmcloud catalog service compose-for-mysql
Getting catalog entry...
OK

ID                 ComposeMySQL-P
Name               compose-for-mysql
Kind               service
Provider           IBM
Tags               big_data, data_management, database, eu_access, gc_migrate, ibm_beta, ibm_created, ibm_dedicated_public
Active             true
Description        MySQL is a fast, easy-to-use, and flexible RDBMS.
Bindable           false
Original Name      compose-for-mysql
RC Compatible      false
RC Provisionable   false
IAM Compatible     false
Children           Name                     Kind         ID                                Location   Original Location   Target
                   enterprise               plan         ComposeMysqlEnterprise
                   |__enterprise-au-syd     deployment   ComposeMysqlEnterprise:au-syd     au-syd                         bluemix-au-syd
                   |__enterprise-eu-de      deployment   ComposeMysqlEnterprise:eu-de      eu-de                          bluemix-eu-de
                   |__enterprise-eu-gb      deployment   ComposeMysqlEnterprise:eu-gb      eu-gb                          bluemix-eu-gb
                   |__enterprise-us-east    deployment   ComposeMysqlEnterprise:us-east    us-east                        bluemix-us-east
                   |__enterprise-us-south   deployment   ComposeMysqlEnterprise:us-south   us-south                       bluemix-us-south
                   standard                 plan         ComposeMysqlStandard
                   |__standard-au-syd       deployment   ComposeMysqlStandard:au-syd       au-syd                         bluemix-au-syd
                   |__standard-eu-de        deployment   ComposeMysqlStandard:eu-de        eu-de                          bluemix-eu-de
                   |__standard-eu-gb        deployment   ComposeMysqlStandard:eu-gb        eu-gb                          bluemix-eu-gb
                   |__standard-us-east      deployment   ComposeMysqlStandard:us-east      us-east                        bluemix-us-east
                   |__standard-us-south     deployment   ComposeMysqlStandard:us-south     us-south                       bluemix-us-south
```

The suggestion to `Use service instance example if the service is a Cloud Foundry service` is not particularly helpful, I am not trying to bind to an existing instance, rather trying to create a new one.

**Comment by chkhd** [comment]
I was not using the correct yaml:

```yaml
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: mysql-test
spec:
  plan: Standard
  serviceClass: compose-for-mysql
  serviceClassType: CF
  context:
    org: my-org-name
    space: my-space-name
```

This worked.

I guess it would be helpful to have more thorough examples & docs in the future.
