### ISSUE TITLE
Multiple secrets created when creating CloudantDB service 

### ISSUE THREAD

**Issue by jzaccone** [IBM/cloud-operators#230]
I used these yaml resources to create an instance of CloudantDB service,

```
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: mycloudant
spec:
  plan: standard
  serviceClass: cloudantnosqldb
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: binding-cloudant
spec:
  serviceName: mycloudant
  role: Manager
```

This resulted in 100 credentials to be created on the cloud console. Note the "100 items" at the bottom. Only 1 `binding-cloudant` secret was created for Kubernetes.

<img width="1183" alt="Screen Shot 2020-11-11 at 10 56 36 AM" src="https://user-images.githubusercontent.com/2520012/98833959-a74d4a80-240c-11eb-890f-4a49f4df0bba.png">
