### ISSUE TITLE
Support Secrets Manager

### ISSUE THREAD

**Issue by haf-tech** [IBM/cloud-operators#236]
Provisioning IBM Secrets Manager works if creating a new or using existing one. But the binding does not work, means no secret will be created.

Definition
```

apiVersion: ibmcloud.ibm.com/v1
kind: Service
metadata:
  name: secret-manager-demo
  namespace: ico-test
spec:
  plan: lite
  serviceClass: secrets-manager
---
apiVersion: ibmcloud.ibm.com/v1
kind: Binding
metadata:
    name: secret-manager-demo
    namespace: ico-test
spec:
    serviceName: secret-manager-demo
```

Error message 
```
2020-12-21T17:54:43.744Z        INFO    controllers.Binding     controllers/binding_controller.go:451   Creating        {"credentials": "secret-manager-demo"}
2020-12-21T17:54:46.295Z        INFO    controllers.Binding     controllers/binding_controller.go:380   Request failed with status code: 400, ServerErrorResponse: {"message":"Service Broker returned error status code 404","status_code":400,"transaction_id":"bss-5dd8afa0e37bae82"}
```
