### ISSUE TITLE
Service binding to Event Streams service stuck in pending state

### ISSUE THREAD

**Issue by guang-shi** [IBM/cloud-operators#250]
Here is our service binding yaml:
```
apiVersion: ibmcloud.ibm.com/v1
kind: Service
metadata:
    name: {{.Values.eventstreams_service_name}}
    namespace: {{ .Release.Namespace }}
spec:
    serviceClass: messagehub
    plan: Alias

---

apiVersion: ibmcloud.ibm.com/v1
kind: Binding
metadata:
  name: {{ .Release.Namespace }}-eventstreams-creds
  annotations:
    ibmcloud.ibm.com/keyId: {{ .Values.eventstreams_credential_keyId }}
spec:
  serviceName: {{.Values.eventstreams_service_name}}
  alias: {{.Values.eventstreams_credential_name}}
```

The service alias is created Online but the binding is stuck in Pending state. Please see attached logs which describe them
[describe-service.txt](https://github.com/IBM/cloud-operators/files/6541299/describe-service.txt)
[describe-binding.txt](https://github.com/IBM/cloud-operators/files/6541300/describe-binding.txt)

Logged an Event Streams support ticket earlier and they confirmed the binding request went through ok (https://cloud.ibm.com/unifiedsupport/cases?accountId=5132b2ea1d0ea6894b7fbcb76d370e7d&number=CS2317066)

Any suggestions? Are there any logs generated by the ibmcloud operator that can help debug this? Thanks in advance.

**Comment by guang-shi** [comment]
BTW, we have similar service binding to Elastic Search service which is working fine.
```
apiVersion: ibmcloud.ibm.com/v1
kind: Service
metadata:
[describe-service-elastic.txt](https://github.com/IBM/cloud-operators/files/6541333/describe-service-elastic.txt)
[describe-binding-elastic.txt](https://github.com/IBM/cloud-operators/files/6541336/describe-binding-elastic.txt)


    name: {{.Values.elasticsearch_service_name}}
    namespace: {{ .Release.Namespace }}
spec:
    serviceClass: databases-for-elasticsearch
    plan: Alias

---

apiVersion: ibmcloud.ibm.com/v1
kind: Binding
metadata:
  name: {{ .Release.Namespace }}-es-creds
  annotations:
    ibmcloud.ibm.com/keyId: {{ .Values.elasticsearch_credential_keyId }}
spec:
  serviceName: {{.Values.elasticsearch_service_name}}
  alias: {{.Values.elasticsearch_credential_name}}
```
