### ISSUE TITLE
Memory Limit too low results in OOMKilled

### ISSUE THREAD

**Issue by haf-tech** [IBM/cloud-operators#268]
Installation of the operator in OpenShift is not successful, due the fact that the requested memory limit does not met the real memory consumption

the current config results in restart with OOMKilled signal
```
resources:
  limits:
    cpu: 100m
    memory: 175Mi
  requests:
    cpu: 100m
    memory: 20Mi
```

Changing to 255Mi results in a stable version
```
resources:
  limits:
    cpu: 100m
    memory: 255Mi
  requests:
    cpu: 100m
    memory: 20Mi
```

Affected version:
IBM Cloud Operator, 1.1.0

**Comment by greglanthier** [comment]
When I've installed **ibmcloud-operator** I've been using a subscription that looks like this:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibmcloud-operator
spec:
  channel: stable
  name: ibmcloud-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  config:
    resources:
      limits:
        cpu: 400m
        memory: 700Mi
      requests:
        cpu: 400m
        memory: 40Mi
```

This is probably oodles more than the operator itself needs 🤷 .

The increased memory consumption in OpenShift when compared against other cluster types might be related to the number of namespaces present in the cluster itself - especially if your installing the operator with cluster-wide scope.
