### ISSUE TITLE
db2 sample provisions correctly but status is failed

### ISSUE THREAD

**Issue by vazirim** [IBM/cloud-operators#53]

**Comment by pdettori** [comment]
Based on chat with @vazirim , seems like this applies to services that take a long time to provision, initially they are inactive (or failed in the case of db2), and it used to be that they would eventually become Online. But for some reason this is not happening (but the Binding works fine.

**Comment by pdettori** [comment]
Example for a cloudant service showing 'inactive'
```
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
   name: cloudanttest
spec:
   plan: lite
   serviceClass: cloudantnosqldb
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
   name: clbinding
spec:
   serviceName: cloudanttest
```
