### ISSUE TITLE
Cannot create a binding to existing Cloudant service

### ISSUE THREAD

**Issue by lionelvillard** [IBM/cloud-operators#69]
I'm trying to apply this yaml:

```yaml
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
    name: cloudant
spec:
    plan: Alias
    serviceName: cloudant
    serviceClass: cloudantnosqldb
```

After applying and waiting 3-4mn I see:

```
Status:
  Message:  Processing Resource
  State:    Pending
```

It'd be nice if the status section reports what's wrong with either `spec` or my configuration.

**Comment by lionelvillard** [comment]
logs:
```

{"level":"info","ts":1571344992.572309,"logger":"binding","msg":"Binding could not read service","cloudant":"Service.ibmcloud.ibm.com \"cloudant\" not found"}
```

**Comment by pdettori** [comment]
The plan `Alias` should be applied to a Service CR, not to a Binding (see https://github.com/IBM/cloud-operators/blob/master/docs/user-guide.md#referencing-an-existing-service ). Is this issue more about not getting some message about the error in the status then about binding ?

**Comment by vazirim** [comment]
This should be written as:
```
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
    name: cloudant
spec:
    plan: Alias
    serviceName: cloudant
    serviceClass: cloudantnosqldb
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: binding-cloudant
spec:
  serviceName: cloudant
```

The binding is failing because we are getting a 500 error from Bluemix. Investigating...
