### ISSUE TITLE
Bug for service provisioning with multiple bindings

### ISSUE THREAD

**Issue by SteveZhang-CDL** [IBM/cloud-operators#96]
I provision a cloudant service with multiple bindings according to the following yaml file:

```
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: my-cloudant
spec:
  plan: standard 
  serviceClass: cloudantnosqldb
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: my-binding-cloudant-1
spec:
  serviceName: my-cloudant
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: my-binding-cloudant-2
spec:
  serviceName: my-cloudant
```

However,  I can see there are two service instances in IBM Cloud Portal resource list, one has two bindings, another one has none, showing as below:

<img width="1304" alt="cloudant" src="https://user-images.githubusercontent.com/4101246/76293615-57057200-62ec-11ea-983b-0d5d34c909c9.png">

<img width="1114" alt="cloudant1" src="https://user-images.githubusercontent.com/4101246/76293782-9f249480-62ec-11ea-9723-234414afed04.png">

<img width="1146" alt="cloudant2" src="https://user-images.githubusercontent.com/4101246/76293802-aa77c000-62ec-11ea-89a8-686e6ec165bf.png">
